---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_facts.distribution | lower == 'archlinux' or
          ansible_facts.os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          ansible.builtin.command: |
            pacman --refresh --sync --sysupgrade --noconfirm
          register: pacman
          changed_when: pacman.rc != 0
          failed_when: pacman.rc != 0

        - name: create depends service
          ansible.builtin.copy:
            mode: 0755
            dest: /etc/init.d/net
            content: |
              #!/usr/bin/openrc-run
              true
          when:
            - ansible_facts.os_family | lower == 'artix linux'

    - name: make sure python3-apt is installed (only debian based)
      ansible.builtin.package:
        name:
          - python3-apt
        state: present
      when:
        - ansible_facts.os_family | lower == 'debian'

    - name: update package cache
      become: true
      ansible.builtin.package:
        update_cache: true

    - name: install dependencies
      ansible.builtin.package:
        name:
          - iproute2
        state: present

    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_facts.distribution }} ({{ ansible_facts.os_family }})"
          - "distribution version : {{ ansible_facts.distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_facts.python.version.major }}.{{ ansible_facts.python.version.minor }}"
