---

forgejo_database:
  db_type: sqlite3
  charset: utf8
  path: /var/lib/forgejo/data/forgejo.db
  log_sql: false

forgejo_repository:
  root: /var/lib/forgejo/data/forgejo-repositories

forgejo_server:
  domain: forgejo.molecule.lan
  protocol: http
  http_addr: "0.0.0.0"
  http_port: 3000
  root_url: http://forgejo.molecule.lan:3000
  disable_ssh: true
  # ssh_domain: forgejo.molecule.lan
  # landing_page: login
  lfs_start_server: false
  # lfs_jwt_secret: OkAglKI7wKkBlT1l5YyncFM-vyDpQbEZefzQKcaoVxE

forgejo_git:
  home_path: /var/lib/forgejo/data/home

forgejo_lfs:
  path: /var/lib/forgejo/data/lfs

forgejo_mailer:
  enabled: false

forgejo_service:
  register_email_confirm: false

forgejo_openid:
  enable_openid_signin: false
  enable_openid_signup: false

forgejo_log:
  mode:
    - "console"
    - "file"
    - "file-error"
  level: Info
  root_path: /var/lib/forgejo/log
  # router: console
  log_writer:
    # https://forgejo.org/docs/latest/admin/logging-documentation
    - name: console                                 # standard console
      mode: console                                 #
      level: Info                                   #
      flags: stdflags                               #
      colorize: false                               #
    - name: file
      mode: file                                    #
      level: Info                                   #
      file_name: forgejo.log                        #
      log_rotate: true                              # true
      # max_size_shift: 5                             # 28
      daily_rotate: true                            # true
      max_days: 2                                   # 7
      compress: true                                # true
      compression_level: 1                          # -1
    - name: file-error
      mode: file
      level: Error
      file_name: forgejo.err                        #

forgejo_security:
  install_lock: true
  internal_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2ODEyMjMxMjR9.tTmy5Nuv6_p66VZCxASiviwKSZCFk9GXggQ1-naqH7g

forgejo_admin_user:
  username: "root"
  password: "{{ vault__forgejo.root }}"
  email: "root@example.com"

forgejo_users:
  - username: "foo"
    password: "{{ vault__forgejo.foo }}"
    email: "foo@example.com"
    state: present

  - username: "foo2"
    password: "{{ vault__forgejo.foo }}"
    email: "foo@example.com"
    state: present

  - username: "bar2"
    password: ""
    email: "bar@example.com"
    state: present

  - username: "bar"
    password: "{{ vault__forgejo.foo }}"
    email: "bar@example.com"
    state: present

  - username: root
    password: "{{ vault__forgejo.root }}"
    email: "root@example.com"

...
